//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';

export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');

export interface IApiClient {
    /**
     * Obtiene el catálogo de ciudades, opcionalmente filtrado por país
     * @param countryCode (optional) Código de país ISO 3166-1 alpha-3 (opcional)
     * @param onlyActive (optional) Si es true, retorna solo ciudades activas (default: true)
     * @return Lista de ciudades obtenida exitosamente
     */
    cities(countryCode: string | undefined, onlyActive: boolean | undefined): Observable<CityDto[]>;
    /**
     * Obtiene el catálogo completo de países
     * @param onlyActive (optional) Si es true, retorna solo países activos (default: true)
     * @return Lista de países obtenida exitosamente
     */
    countriesAll(onlyActive: boolean | undefined): Observable<CountryDto[]>;
    /**
     * Obtiene un país específico por su código
     * @param code Código de país ISO 3166-1 alpha-3 (ej: ESP, USA, MEX)
     * @return País encontrado
     */
    countries(code: string): Observable<CountryDto>;
    /**
     * Obtiene el catálogo completo de tipos de destino
     * @param onlyActive (optional) Si es true, retorna solo tipos activos (default: true)
     * @return Lista de tipos de destino obtenida exitosamente
     */
    destinationTypesAll(onlyActive: boolean | undefined): Observable<DestinationTypeDto[]>;
    /**
     * Obtiene un tipo de destino específico por su ID
     * @param id ID del tipo de destino
     * @return Tipo de destino encontrado
     */
    destinationTypes(id: number): Observable<DestinationTypeDto>;
    /**
     * Obtiene todos los destinos con filtros opcionales y paginación
     * @param searchTerm (optional) Término de búsqueda que se aplica a nombre, descripción y código de país
     * @param countryCode (optional) Filtro por código de país específico
     * @param destinationTypeId (optional) Filtro por ID de tipo de destino específico
     * @param page (optional) Número de página actual (comienza en 1)
     * @param pageSize (optional) Número de elementos por página (máximo 100 recomendado)
     * @return Lista de destinos obtenida exitosamente
     */
    destinationsGET(searchTerm: string | undefined, countryCode: string | undefined, destinationTypeId: number | undefined, page: number | undefined, pageSize: number | undefined): Observable<DestinationDtoPagedResultDto>;
    /**
     * Crea un nuevo destino turístico
     * @param body (optional) Datos del nuevo destino
     * @return Destino creado exitosamente
     */
    destinationsPOST(body: CreateDestinationDto | undefined): Observable<DestinationDto>;
    /**
     * Obtiene un destino por su ID
     * @param id ID del destino
     * @return Destino encontrado exitosamente
     */
    destinationsGET2(id: number): Observable<DestinationDto>;
    /**
     * Actualiza un destino existente
     * @param id ID del destino a actualizar
     * @param body (optional) Datos actualizados del destino
     * @return Destino actualizado exitosamente
     */
    destinationsPUT(id: number, body: UpdateDestinationDto | undefined): Observable<DestinationDto>;
    /**
     * Elimina un destino
     * @param id ID del destino a eliminar
     * @return Destino eliminado exitosamente
     */
    destinationsDELETE(id: number): Observable<void>;
    /**
     * Obtiene la lista de códigos de países disponibles
     * @return Lista de países obtenida exitosamente
     */
    countriesAll2(): Observable<string[]>;
    /**
     * Obtiene la lista de tipos de destino disponibles desde el catálogo
     * @return Lista de tipos obtenida exitosamente
     */
    types(): Observable<DestinationTypeDto[]>;
}

@Injectable({
    providedIn: 'root'
})
export class ApiClient implements IApiClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * Obtiene el catálogo de ciudades, opcionalmente filtrado por país
     * @param countryCode (optional) Código de país ISO 3166-1 alpha-3 (opcional)
     * @param onlyActive (optional) Si es true, retorna solo ciudades activas (default: true)
     * @return Lista de ciudades obtenida exitosamente
     */
    cities(countryCode: string | undefined, onlyActive: boolean | undefined): Observable<CityDto[]> {
        let url_ = this.baseUrl + "/api/v1/Catalog/cities?";
        if (countryCode === null)
            throw new globalThis.Error("The parameter 'countryCode' cannot be null.");
        else if (countryCode !== undefined)
            url_ += "countryCode=" + encodeURIComponent("" + countryCode) + "&";
        if (onlyActive === null)
            throw new globalThis.Error("The parameter 'onlyActive' cannot be null.");
        else if (onlyActive !== undefined)
            url_ += "onlyActive=" + encodeURIComponent("" + onlyActive) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processCities(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processCities(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<CityDto[]>;
                }
            } else
                return _observableThrow(response_) as any as Observable<CityDto[]>;
        }));
    }

    protected processCities(response: HttpResponseBase): Observable<CityDto[]> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(CityDto.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * Obtiene el catálogo completo de países
     * @param onlyActive (optional) Si es true, retorna solo países activos (default: true)
     * @return Lista de países obtenida exitosamente
     */
    countriesAll(onlyActive: boolean | undefined): Observable<CountryDto[]> {
        let url_ = this.baseUrl + "/api/v1/Catalog/countries?";
        if (onlyActive === null)
            throw new globalThis.Error("The parameter 'onlyActive' cannot be null.");
        else if (onlyActive !== undefined)
            url_ += "onlyActive=" + encodeURIComponent("" + onlyActive) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processCountriesAll(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processCountriesAll(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<CountryDto[]>;
                }
            } else
                return _observableThrow(response_) as any as Observable<CountryDto[]>;
        }));
    }

    protected processCountriesAll(response: HttpResponseBase): Observable<CountryDto[]> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(CountryDto.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * Obtiene un país específico por su código
     * @param code Código de país ISO 3166-1 alpha-3 (ej: ESP, USA, MEX)
     * @return País encontrado
     */
    countries(code: string): Observable<CountryDto> {
        let url_ = this.baseUrl + "/api/v1/Catalog/countries/{code}";
        if (code === undefined || code === null)
            throw new globalThis.Error("The parameter 'code' must be defined.");
        url_ = url_.replace("{code}", encodeURIComponent("" + code));
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processCountries(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processCountries(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<CountryDto>;
                }
            } else
                return _observableThrow(response_) as any as Observable<CountryDto>;
        }));
    }

    protected processCountries(response: HttpResponseBase): Observable<CountryDto> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = CountryDto.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status === 404) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("Pa\u00eds no encontrado", status, _responseText, _headers, result404);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * Obtiene el catálogo completo de tipos de destino
     * @param onlyActive (optional) Si es true, retorna solo tipos activos (default: true)
     * @return Lista de tipos de destino obtenida exitosamente
     */
    destinationTypesAll(onlyActive: boolean | undefined): Observable<DestinationTypeDto[]> {
        let url_ = this.baseUrl + "/api/v1/Catalog/destination-types?";
        if (onlyActive === null)
            throw new globalThis.Error("The parameter 'onlyActive' cannot be null.");
        else if (onlyActive !== undefined)
            url_ += "onlyActive=" + encodeURIComponent("" + onlyActive) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processDestinationTypesAll(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processDestinationTypesAll(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<DestinationTypeDto[]>;
                }
            } else
                return _observableThrow(response_) as any as Observable<DestinationTypeDto[]>;
        }));
    }

    protected processDestinationTypesAll(response: HttpResponseBase): Observable<DestinationTypeDto[]> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(DestinationTypeDto.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * Obtiene un tipo de destino específico por su ID
     * @param id ID del tipo de destino
     * @return Tipo de destino encontrado
     */
    destinationTypes(id: number): Observable<DestinationTypeDto> {
        let url_ = this.baseUrl + "/api/v1/Catalog/destination-types/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processDestinationTypes(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processDestinationTypes(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<DestinationTypeDto>;
                }
            } else
                return _observableThrow(response_) as any as Observable<DestinationTypeDto>;
        }));
    }

    protected processDestinationTypes(response: HttpResponseBase): Observable<DestinationTypeDto> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = DestinationTypeDto.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status === 404) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("Tipo de destino no encontrado", status, _responseText, _headers, result404);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * Obtiene todos los destinos con filtros opcionales y paginación
     * @param searchTerm (optional) Término de búsqueda que se aplica a nombre, descripción y código de país
     * @param countryCode (optional) Filtro por código de país específico
     * @param destinationTypeId (optional) Filtro por ID de tipo de destino específico
     * @param page (optional) Número de página actual (comienza en 1)
     * @param pageSize (optional) Número de elementos por página (máximo 100 recomendado)
     * @return Lista de destinos obtenida exitosamente
     */
    destinationsGET(searchTerm: string | undefined, countryCode: string | undefined, destinationTypeId: number | undefined, page: number | undefined, pageSize: number | undefined): Observable<DestinationDtoPagedResultDto> {
        let url_ = this.baseUrl + "/api/v1/Destinations?";
        if (searchTerm === null)
            throw new globalThis.Error("The parameter 'searchTerm' cannot be null.");
        else if (searchTerm !== undefined)
            url_ += "SearchTerm=" + encodeURIComponent("" + searchTerm) + "&";
        if (countryCode === null)
            throw new globalThis.Error("The parameter 'countryCode' cannot be null.");
        else if (countryCode !== undefined)
            url_ += "CountryCode=" + encodeURIComponent("" + countryCode) + "&";
        if (destinationTypeId === null)
            throw new globalThis.Error("The parameter 'destinationTypeId' cannot be null.");
        else if (destinationTypeId !== undefined)
            url_ += "DestinationTypeId=" + encodeURIComponent("" + destinationTypeId) + "&";
        if (page === null)
            throw new globalThis.Error("The parameter 'page' cannot be null.");
        else if (page !== undefined)
            url_ += "Page=" + encodeURIComponent("" + page) + "&";
        if (pageSize === null)
            throw new globalThis.Error("The parameter 'pageSize' cannot be null.");
        else if (pageSize !== undefined)
            url_ += "PageSize=" + encodeURIComponent("" + pageSize) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processDestinationsGET(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processDestinationsGET(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<DestinationDtoPagedResultDto>;
                }
            } else
                return _observableThrow(response_) as any as Observable<DestinationDtoPagedResultDto>;
        }));
    }

    protected processDestinationsGET(response: HttpResponseBase): Observable<DestinationDtoPagedResultDto> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = DestinationDtoPagedResultDto.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status === 500) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Error interno del servidor", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * Crea un nuevo destino turístico
     * @param body (optional) Datos del nuevo destino
     * @return Destino creado exitosamente
     */
    destinationsPOST(body: CreateDestinationDto | undefined): Observable<DestinationDto> {
        let url_ = this.baseUrl + "/api/v1/Destinations";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processDestinationsPOST(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processDestinationsPOST(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<DestinationDto>;
                }
            } else
                return _observableThrow(response_) as any as Observable<DestinationDto>;
        }));
    }

    protected processDestinationsPOST(response: HttpResponseBase): Observable<DestinationDto> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 201) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result201: any = null;
            let resultData201 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result201 = DestinationDto.fromJS(resultData201);
            return _observableOf(result201);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = ProblemDetails.fromJS(resultData400);
            return throwException("Datos de entrada inv\u00e1lidos", status, _responseText, _headers, result400);
            }));
        } else if (status === 500) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Error interno del servidor", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * Obtiene un destino por su ID
     * @param id ID del destino
     * @return Destino encontrado exitosamente
     */
    destinationsGET2(id: number): Observable<DestinationDto> {
        let url_ = this.baseUrl + "/api/v1/Destinations/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processDestinationsGET2(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processDestinationsGET2(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<DestinationDto>;
                }
            } else
                return _observableThrow(response_) as any as Observable<DestinationDto>;
        }));
    }

    protected processDestinationsGET2(response: HttpResponseBase): Observable<DestinationDto> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = DestinationDto.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status === 404) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("Destino no encontrado", status, _responseText, _headers, result404);
            }));
        } else if (status === 500) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Error interno del servidor", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * Actualiza un destino existente
     * @param id ID del destino a actualizar
     * @param body (optional) Datos actualizados del destino
     * @return Destino actualizado exitosamente
     */
    destinationsPUT(id: number, body: UpdateDestinationDto | undefined): Observable<DestinationDto> {
        let url_ = this.baseUrl + "/api/v1/Destinations/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ : any = {
            body: content_,
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Content-Type": "application/json",
                "Accept": "application/json"
            })
        };

        return this.http.request("put", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processDestinationsPUT(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processDestinationsPUT(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<DestinationDto>;
                }
            } else
                return _observableThrow(response_) as any as Observable<DestinationDto>;
        }));
    }

    protected processDestinationsPUT(response: HttpResponseBase): Observable<DestinationDto> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = DestinationDto.fromJS(resultData200);
            return _observableOf(result200);
            }));
        } else if (status === 400) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = ProblemDetails.fromJS(resultData400);
            return throwException("Datos de entrada inv\u00e1lidos", status, _responseText, _headers, result400);
            }));
        } else if (status === 404) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("Destino no encontrado", status, _responseText, _headers, result404);
            }));
        } else if (status === 500) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Error interno del servidor", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * Elimina un destino
     * @param id ID del destino a eliminar
     * @return Destino eliminado exitosamente
     */
    destinationsDELETE(id: number): Observable<void> {
        let url_ = this.baseUrl + "/api/v1/Destinations/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
            })
        };

        return this.http.request("delete", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processDestinationsDELETE(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processDestinationsDELETE(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<void>;
                }
            } else
                return _observableThrow(response_) as any as Observable<void>;
        }));
    }

    protected processDestinationsDELETE(response: HttpResponseBase): Observable<void> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return _observableOf(null as any);
            }));
        } else if (status === 404) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("Destino no encontrado", status, _responseText, _headers, result404);
            }));
        } else if (status === 500) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Error interno del servidor", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * Obtiene la lista de códigos de países disponibles
     * @return Lista de países obtenida exitosamente
     */
    countriesAll2(): Observable<string[]> {
        let url_ = this.baseUrl + "/api/v1/Destinations/countries";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processCountriesAll2(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processCountriesAll2(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<string[]>;
                }
            } else
                return _observableThrow(response_) as any as Observable<string[]>;
        }));
    }

    protected processCountriesAll2(response: HttpResponseBase): Observable<string[]> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(item);
            }
            else {
                result200 = null as any;
            }
            return _observableOf(result200);
            }));
        } else if (status === 500) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Error interno del servidor", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }

    /**
     * Obtiene la lista de tipos de destino disponibles desde el catálogo
     * @return Lista de tipos obtenida exitosamente
     */
    types(): Observable<DestinationTypeDto[]> {
        let url_ = this.baseUrl + "/api/v1/Destinations/types";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processTypes(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processTypes(response_ as any);
                } catch (e) {
                    return _observableThrow(e) as any as Observable<DestinationTypeDto[]>;
                }
            } else
                return _observableThrow(response_) as any as Observable<DestinationTypeDto[]>;
        }));
    }

    protected processTypes(response: HttpResponseBase): Observable<DestinationTypeDto[]> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (response as any).error instanceof Blob ? (response as any).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(DestinationTypeDto.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return _observableOf(result200);
            }));
        } else if (status === 500) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("Error interno del servidor", status, _responseText, _headers);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf(null as any);
    }
}

/** DTO para catálogo de ciudades */
export class CityDto implements ICityDto {
    /** Identificador único */
    id?: number;
    /** Código de país */
    countryCode!: string | undefined;
    /** Nombre de la ciudad */
    name!: string | undefined;
    /** Indica si la ciudad está activa */
    isActive?: boolean;

    constructor(data?: ICityDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.countryCode = _data["countryCode"];
            this.name = _data["name"];
            this.isActive = _data["isActive"];
        }
    }

    static fromJS(data: any): CityDto {
        data = typeof data === 'object' ? data : {};
        let result = new CityDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["countryCode"] = this.countryCode;
        data["name"] = this.name;
        data["isActive"] = this.isActive;
        return data;
    }
}

/** DTO para catálogo de ciudades */
export interface ICityDto {
    /** Identificador único */
    id?: number;
    /** Código de país */
    countryCode: string | undefined;
    /** Nombre de la ciudad */
    name: string | undefined;
    /** Indica si la ciudad está activa */
    isActive?: boolean;
}

/** DTO para catálogo de países */
export class CountryDto implements ICountryDto {
    /** Código de país ISO 3166-1 alpha-3 */
    code!: string | undefined;
    /** Nombre completo del país */
    name!: string | undefined;
    /** Región geográfica */
    region?: string | undefined;
    /** Indica si el país está activo */
    isActive?: boolean;

    constructor(data?: ICountryDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.code = _data["code"];
            this.name = _data["name"];
            this.region = _data["region"];
            this.isActive = _data["isActive"];
        }
    }

    static fromJS(data: any): CountryDto {
        data = typeof data === 'object' ? data : {};
        let result = new CountryDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["code"] = this.code;
        data["name"] = this.name;
        data["region"] = this.region;
        data["isActive"] = this.isActive;
        return data;
    }
}

/** DTO para catálogo de países */
export interface ICountryDto {
    /** Código de país ISO 3166-1 alpha-3 */
    code: string | undefined;
    /** Nombre completo del país */
    name: string | undefined;
    /** Región geográfica */
    region?: string | undefined;
    /** Indica si el país está activo */
    isActive?: boolean;
}

/** DTO para crear un nuevo destino No incluye ID ni LastModif ya que se generan automáticamente */
export class CreateDestinationDto implements ICreateDestinationDto {
    /** Nombre del destino turístico */
    name!: string;
    /** Descripción detallada del destino */
    description!: string;
    /** Descripción larga y detallada del destino con información completa */
    longDescription?: string | undefined;
    /** URL o data URL de la imagen principal del destino */
    imageUrl?: string | undefined;
    /** Código ISO del país (3 caracteres) */
    countryCode!: string;
    /** ID del tipo de destino turístico */
    destinationTypeId!: number;

    constructor(data?: ICreateDestinationDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.description = _data["description"];
            this.longDescription = _data["longDescription"];
            this.imageUrl = _data["imageUrl"];
            this.countryCode = _data["countryCode"];
            this.destinationTypeId = _data["destinationTypeId"];
        }
    }

    static fromJS(data: any): CreateDestinationDto {
        data = typeof data === 'object' ? data : {};
        let result = new CreateDestinationDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["description"] = this.description;
        data["longDescription"] = this.longDescription;
        data["imageUrl"] = this.imageUrl;
        data["countryCode"] = this.countryCode;
        data["destinationTypeId"] = this.destinationTypeId;
        return data;
    }
}

/** DTO para crear un nuevo destino No incluye ID ni LastModif ya que se generan automáticamente */
export interface ICreateDestinationDto {
    /** Nombre del destino turístico */
    name: string;
    /** Descripción detallada del destino */
    description: string;
    /** Descripción larga y detallada del destino con información completa */
    longDescription?: string | undefined;
    /** URL o data URL de la imagen principal del destino */
    imageUrl?: string | undefined;
    /** Código ISO del país (3 caracteres) */
    countryCode: string;
    /** ID del tipo de destino turístico */
    destinationTypeId: number;
}

/** DTO para transferir información completa de un destino Se usa para respuestas de la API */
export class DestinationDto implements IDestinationDto {
    /** Identificador único del destino */
    id!: number;
    /** Nombre del destino turístico */
    name!: string | undefined;
    /** Descripción detallada del destino */
    description!: string | undefined;
    /** Descripción larga y detallada del destino con información completa */
    longDescription?: string | undefined;
    /** Código ISO del país (3 caracteres) */
    countryCode!: string | undefined;
    /** ID del tipo de destino turístico */
    destinationTypeId!: number;
    /** Nombre del tipo de destino (para mostrar en UI) */
    typeName?: string | undefined;
    /** Fecha de última modificación */
    lastModif!: Date;
    /** URL de la imagen principal del destino */
    imageUrl?: string | undefined;
    /** Total de reservas del destino */
    totalBookings?: number;
    /** Calificación promedio (escala 0-5) */
    averageRating?: number;
    /** Número de reseñas */
    reviewCount?: number;
    /** Estado del destino (Active, Inactive) */
    status?: string | undefined;
    /** Nombre del usuario que creó el registro */
    createdBy?: string | undefined;
    /** Fecha de creación del registro */
    createdDate!: Date;

    constructor(data?: IDestinationDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.description = _data["description"];
            this.longDescription = _data["longDescription"];
            this.countryCode = _data["countryCode"];
            this.destinationTypeId = _data["destinationTypeId"];
            this.typeName = _data["typeName"];
            this.lastModif = _data["lastModif"] ? new Date(_data["lastModif"].toString()) : undefined as any;
            this.imageUrl = _data["imageUrl"];
            this.totalBookings = _data["totalBookings"];
            this.averageRating = _data["averageRating"];
            this.reviewCount = _data["reviewCount"];
            this.status = _data["status"];
            this.createdBy = _data["createdBy"];
            this.createdDate = _data["createdDate"] ? new Date(_data["createdDate"].toString()) : undefined as any;
        }
    }

    static fromJS(data: any): DestinationDto {
        data = typeof data === 'object' ? data : {};
        let result = new DestinationDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["description"] = this.description;
        data["longDescription"] = this.longDescription;
        data["countryCode"] = this.countryCode;
        data["destinationTypeId"] = this.destinationTypeId;
        data["typeName"] = this.typeName;
        data["lastModif"] = this.lastModif ? this.lastModif.toISOString() : undefined as any;
        data["imageUrl"] = this.imageUrl;
        data["totalBookings"] = this.totalBookings;
        data["averageRating"] = this.averageRating;
        data["reviewCount"] = this.reviewCount;
        data["status"] = this.status;
        data["createdBy"] = this.createdBy;
        data["createdDate"] = this.createdDate ? this.createdDate.toISOString() : undefined as any;
        return data;
    }
}

/** DTO para transferir información completa de un destino Se usa para respuestas de la API */
export interface IDestinationDto {
    /** Identificador único del destino */
    id: number;
    /** Nombre del destino turístico */
    name: string | undefined;
    /** Descripción detallada del destino */
    description: string | undefined;
    /** Descripción larga y detallada del destino con información completa */
    longDescription?: string | undefined;
    /** Código ISO del país (3 caracteres) */
    countryCode: string | undefined;
    /** ID del tipo de destino turístico */
    destinationTypeId: number;
    /** Nombre del tipo de destino (para mostrar en UI) */
    typeName?: string | undefined;
    /** Fecha de última modificación */
    lastModif: Date;
    /** URL de la imagen principal del destino */
    imageUrl?: string | undefined;
    /** Total de reservas del destino */
    totalBookings?: number;
    /** Calificación promedio (escala 0-5) */
    averageRating?: number;
    /** Número de reseñas */
    reviewCount?: number;
    /** Estado del destino (Active, Inactive) */
    status?: string | undefined;
    /** Nombre del usuario que creó el registro */
    createdBy?: string | undefined;
    /** Fecha de creación del registro */
    createdDate: Date;
}

/** DTO genérico para resultados paginados Se puede usar con cualquier tipo de entidad */
export class DestinationDtoPagedResultDto implements IDestinationDtoPagedResultDto {
    /** Lista de elementos de la página actual */
    items?: DestinationDto[] | undefined;
    /** Número total de elementos que coinciden con los filtros */
    totalCount!: number;
    /** Número de página actual */
    page!: number;
    /** Número de elementos por página */
    pageSize!: number;
    /** Número total de páginas calculado automáticamente */
    readonly totalPages?: number;

    constructor(data?: IDestinationDtoPagedResultDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["items"])) {
                this.items = [] as any;
                for (let item of _data["items"])
                    this.items!.push(DestinationDto.fromJS(item));
            }
            this.totalCount = _data["totalCount"];
            this.page = _data["page"];
            this.pageSize = _data["pageSize"];
            (this as any).totalPages = _data["totalPages"];
        }
    }

    static fromJS(data: any): DestinationDtoPagedResultDto {
        data = typeof data === 'object' ? data : {};
        let result = new DestinationDtoPagedResultDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.items)) {
            data["items"] = [];
            for (let item of this.items)
                data["items"].push(item ? item.toJSON() : undefined as any);
        }
        data["totalCount"] = this.totalCount;
        data["page"] = this.page;
        data["pageSize"] = this.pageSize;
        data["totalPages"] = this.totalPages;
        return data;
    }
}

/** DTO genérico para resultados paginados Se puede usar con cualquier tipo de entidad */
export interface IDestinationDtoPagedResultDto {
    /** Lista de elementos de la página actual */
    items?: DestinationDto[] | undefined;
    /** Número total de elementos que coinciden con los filtros */
    totalCount: number;
    /** Número de página actual */
    page: number;
    /** Número de elementos por página */
    pageSize: number;
    /** Número total de páginas calculado automáticamente */
    totalPages?: number;
}

/** DTO para catálogo de tipos de destino */
export class DestinationTypeDto implements IDestinationTypeDto {
    /** Identificador único */
    id?: number;
    /** Código único */
    code!: string | undefined;
    /** Nombre para mostrar */
    name!: string | undefined;
    /** Identificador de icono o clase CSS */
    icon?: string | undefined;
    /** Color de fondo en formato hexadecimal (ej: #dbeafe) */
    colorBackground?: string | undefined;
    /** Color de texto en formato hexadecimal (ej: #0284c7) */
    colorForeground?: string | undefined;
    /** Orden de visualización */
    displayOrder?: number;
    /** Indica si el tipo está activo */
    isActive?: boolean;

    constructor(data?: IDestinationTypeDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.code = _data["code"];
            this.name = _data["name"];
            this.icon = _data["icon"];
            this.colorBackground = _data["colorBackground"];
            this.colorForeground = _data["colorForeground"];
            this.displayOrder = _data["displayOrder"];
            this.isActive = _data["isActive"];
        }
    }

    static fromJS(data: any): DestinationTypeDto {
        data = typeof data === 'object' ? data : {};
        let result = new DestinationTypeDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["code"] = this.code;
        data["name"] = this.name;
        data["icon"] = this.icon;
        data["colorBackground"] = this.colorBackground;
        data["colorForeground"] = this.colorForeground;
        data["displayOrder"] = this.displayOrder;
        data["isActive"] = this.isActive;
        return data;
    }
}

/** DTO para catálogo de tipos de destino */
export interface IDestinationTypeDto {
    /** Identificador único */
    id?: number;
    /** Código único */
    code: string | undefined;
    /** Nombre para mostrar */
    name: string | undefined;
    /** Identificador de icono o clase CSS */
    icon?: string | undefined;
    /** Color de fondo en formato hexadecimal (ej: #dbeafe) */
    colorBackground?: string | undefined;
    /** Color de texto en formato hexadecimal (ej: #0284c7) */
    colorForeground?: string | undefined;
    /** Orden de visualización */
    displayOrder?: number;
    /** Indica si el tipo está activo */
    isActive?: boolean;
}

export class ProblemDetails implements IProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    [key: string]: any;

    constructor(data?: IProblemDetails) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.type = _data["type"];
            this.title = _data["title"];
            this.status = _data["status"];
            this.detail = _data["detail"];
            this.instance = _data["instance"];
        }
    }

    static fromJS(data: any): ProblemDetails {
        data = typeof data === 'object' ? data : {};
        let result = new ProblemDetails();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["type"] = this.type;
        data["title"] = this.title;
        data["status"] = this.status;
        data["detail"] = this.detail;
        data["instance"] = this.instance;
        return data;
    }
}

export interface IProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    [key: string]: any;
}

/** DTO para actualizar un destino existente No incluye ID ni LastModif ya que se manejan internamente */
export class UpdateDestinationDto implements IUpdateDestinationDto {
    /** Nombre del destino turístico */
    name!: string;
    /** Descripción detallada del destino */
    description!: string;
    /** Descripción larga y detallada del destino con información completa */
    longDescription?: string | undefined;
    /** URL o data URL de la imagen principal del destino */
    imageUrl?: string | undefined;
    /** Código ISO del país (3 caracteres) */
    countryCode!: string;
    /** ID del tipo de destino turístico */
    destinationTypeId!: number;

    constructor(data?: IUpdateDestinationDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.description = _data["description"];
            this.longDescription = _data["longDescription"];
            this.imageUrl = _data["imageUrl"];
            this.countryCode = _data["countryCode"];
            this.destinationTypeId = _data["destinationTypeId"];
        }
    }

    static fromJS(data: any): UpdateDestinationDto {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateDestinationDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["description"] = this.description;
        data["longDescription"] = this.longDescription;
        data["imageUrl"] = this.imageUrl;
        data["countryCode"] = this.countryCode;
        data["destinationTypeId"] = this.destinationTypeId;
        return data;
    }
}

/** DTO para actualizar un destino existente No incluye ID ni LastModif ya que se manejan internamente */
export interface IUpdateDestinationDto {
    /** Nombre del destino turístico */
    name: string;
    /** Descripción detallada del destino */
    description: string;
    /** Descripción larga y detallada del destino con información completa */
    longDescription?: string | undefined;
    /** URL o data URL de la imagen principal del destino */
    imageUrl?: string | undefined;
    /** Código ISO del país (3 caracteres) */
    countryCode: string;
    /** ID del tipo de destino turístico */
    destinationTypeId: number;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    return _observableThrow(new ApiException(message, status, response, headers, result));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader();
            reader.onload = event => {
                observer.next((event.target as any).result);
                observer.complete();
            };
            reader.readAsText(blob);
        }
    });
}